// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: todos.sql

package database

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (task, status)
VALUES ($1, $2)
RETURNING id, task, status, created_at, updated_at
`

type CreateTodoParams struct {
	Task   string `json:"task"`
	Status Status `json:"status"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Task, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompletedTodos = `-- name: DeleteCompletedTodos :exec
DELETE FROM todos
WHERE status = 'Completed'
`

func (q *Queries) DeleteCompletedTodos(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCompletedTodos)
	return err
}

const getAllActiveTodos = `-- name: GetAllActiveTodos :many
SELECT id, task, status, created_at, updated_at FROM todos
WHERE status = 'Active'
`

func (q *Queries) GetAllActiveTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getAllActiveTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCompletedTodos = `-- name: GetAllCompletedTodos :many
SELECT id, task, status, created_at, updated_at FROM todos
WHERE status = 'Completed'
`

func (q *Queries) GetAllCompletedTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getAllCompletedTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, task, status, created_at, updated_at FROM todos
`

func (q *Queries) GetAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
